### ISSUE TITLE
please update vue-native-template-compiler to 0.0.12

### ISSUE THREAD

**Issue by lenvonsam** [syumai/vue-native-custom-transformer-plugin#2]
@syumai Hi, can you update version of vue-native-template-compiler to 0.0.12 , that can fix bug of render-prop-fn not work.
thx

**Comment by syumai** [comment]
@lenvonsam Oh... OK, I'll check it later

**Comment by syumai** [comment]
@lenvonsam 
I've updated dependencies and released as v0.2.2.
Commit: https://github.com/syumai/vue-native-custom-transformer-plugin/commit/152034d9c4723aa6da4b5128ba6cf72cceb7cedb
Release: https://github.com/syumai/vue-native-custom-transformer-plugin/releases/tag/v0.2.2

Please install new version, thx!
