### ISSUE TITLE
.ts files

### ISSUE THREAD

**Issue by joshua1** [syumai/vue-native-custom-transformer-plugin#3]
Hi @syumai if i include ts in vueExtensions in the vueTransformerPlugin.js . will that handle transforms for typescript files  files without issues ?

**Comment by syumai** [comment]
No, it doesn't.
This plugin handles only Vue's SFC (Single File Component).
`.ts` file will not be converted.
Please check this example: https://github.com/syumai/vue-native-example-app

**Comment by joshua1** [comment]
I did check the example hence my question here. the vueTransformerPlugin.js files simply checks the files in source and passes those with the defined extensions in the array to vueNativeScripts.transform method. I guess typescript transformation of ts fies needs happen in this method call, i will have a look
