### ISSUE TITLE
SCSS/SASS include?

### ISSUE THREAD

**Issue by Britzer** [syumai/vue-native-custom-transformer-plugin#4]
Is it possible to include scss/sass to your custom transformer?

If so, how?

**Comment by syumai** [comment]
I've tried to add Sass but I couldn't.
Because it requires native plugins to parsing.
This plugin works on metro bundler, so it was too hard to support in easy way.

BTW, you can write SCSS / Sass like style in stylus.
See this: http://stylus-lang.com/

**Comment by boygiandi** [comment]
Found the way

**vue-native-custom-transformer.config.js**
```
var sass = require('node-sass');

module.exports = {
  // configure transformer plugins
  plugins: {
    styles: [{
        lang: 'scss', // This must be set in "lang" attribute.
        transform(content) {
          var output = sass.renderSync({
            data: content
          });
          return output.css.toString();
        },
      }],
  },
};
```

Please add this  to your home page, so everyone can know. Thank you
