### ISSUE TITLE
vue-native-scripts upgrade to 0.0.15

### ISSUE THREAD

**Issue by lenvonsam** [syumai/vue-native-custom-transformer-plugin#5]
please upgrade vue-native-scripts to v0.0.15,because react-native 0.59.3 need newer vue-native-scripts
when use vue-native-custom-transformer-plugin occur error
![image](https://user-images.githubusercontent.com/10168476/57713102-61db8000-76a4-11e9-80a3-a4a4323ca953.png)
![image](https://user-images.githubusercontent.com/10168476/57713168-80417b80-76a4-11e9-989e-f5521c2b8f12.png)

but i change to latest vue-native-scripts that works fine
![image](https://user-images.githubusercontent.com/10168476/57713226-a0713a80-76a4-11e9-87c3-cffa660e7d99.png)
![image](https://user-images.githubusercontent.com/10168476/57713259-b121b080-76a4-11e9-8c63-3d6d36e7eb53.png)

how to solve this bug

**Comment by lenvonsam** [comment]
@syumai  i have solved this bug, please approve this pull request, thx

**Comment by syumai** [comment]
Thanks!

**Comment by lenvonsam** [comment]
please upgrade vue-native-custom-transformer-plugin version on npmjs website
@syumai

**Comment by syumai** [comment]
I published 0.2.3.
Here: https://www.npmjs.com/package/vue-native-custom-transformer-plugin/v/0.2.3

**Comment by lenvonsam** [comment]
thx
